[mcserver]
logfile = "mcserver.log"
tunnel = "playit"
java = "22"

[server]
online_mode = false
version = "1.20.0"
server_type = "java"
category = "vanilla"
providor = "vanilla"
#url = "https://launcher.mojang.com/v1/objects/9d3d8f07c1e2b3f3d3f6a3b5f7f2b0b3f7b2d4f2/server.jar"

